In [1]:
%load_ext sql

In [2]:
%%sql
mysql+pymysql://w-alkao:mypassword@localhost

In [3]:
%sql SHOW DATABASES;

 * mysql+pymysql://w-alkao:***@localhost
8 rows affected.

[('ap',),
 ('ex',),
 ('information_schema',),
 ('livestock',),
 ('mysql',),
 ('om',),
 ('performance_schema',),
 ('sys',)]

In [4]:
%sql USE ap

 * mysql+pymysql://w-alkao:***@localhost
0 rows affected.

[]

### Intro to subqueries

In [7]:
%%sql # A query that uses an inner join that retrieve invoice number, invoice date and invoice total for vendor in CA region

SELECT invoice_number, invoice_date, invoice_total
FROM Invoices i
  JOIN Vendors v ON i.vendor_id = v.vendor_id
WHERE vendor_state = 'CA'
ORDER BY invoice_date

 * mysql+pymysql://w-alkao:***@localhost
40 rows affected.

[('97/488', datetime.date(2018, 4, 24), Decimal('601.95')),
 ('125520-1', datetime.date(2018, 4, 24), Decimal('95.00')),
 ('111-92R-10096', datetime.date(2018, 4, 30), Decimal('16.33')),
 ('25022117', datetime.date(2018, 5, 1), Decimal('6.00')),
 ('P02-88D77S7', datetime.date(2018, 5, 3), Decimal('856.92')),
 ('QP58872', datetime.date(2018, 5, 7), Decimal('116.54')),
 ('24863706', datetime.date(2018, 5, 10), Decimal('6.00')),
 ('10843', datetime.date(2018, 5, 11), Decimal('4901.26')),
 ('77290', datetime.date(2018, 5, 13), Decimal('1750.00')),
 ('121897', datetime.date(2018, 5, 19), Decimal('450.00')),
 ('97/486', datetime.date(2018, 5, 21), Decimal('953.10')),
 ('P02-3772', datetime.date(2018, 5, 21), Decimal('7125.34')),
 ('94007005', datetime.date(2018, 5, 23), Decimal('220.00')),
 ('97/465', datetime.date(2018, 5, 25), Decimal('565.15')),
 ('RTR-72-3662-X', datetime.date(2018, 5, 25), Decimal('1600.00')),
 ('97/503', datetime.date(2018, 5, 30), Decimal('639.77')),
 ('111-92R-10094', datetime.date(2018, 6, 1), Decimal('19.67')),
 ('547481328', datetime.date(2018, 6, 3), Decimal('224.00')),
 ('111-92R-10097', datetime.date(2018, 6, 4), Decimal('16.33')),
 ('547479217', datetime.date(2018, 6, 7), Decimal('116.00')),
 ('Q545443', datetime.date(2018, 6, 9), Decimal('1083.58')),
 ('111-92R-10092', datetime.date(2018, 6, 9), Decimal('46.21')),
 ('97/553B', datetime.date(2018, 6, 10), Decimal('313.55')),
 ('367447', datetime.date(2018, 6, 11), Decimal('2433.00')),
 ('24946731', datetime.date(2018, 6, 15), Decimal('25.67')),
 ('509786', datetime.date(2018, 6, 18), Decimal('6940.25')),
 ('MABO1489', datetime.date(2018, 6, 21), Decimal('936.93')),
 ('24780512', datetime.date(2018, 6, 22), Decimal('6.00')),
 ('CBM9920-M-T77109', datetime.date(2018, 6, 23), Decimal('290.00')),
 ('109596', datetime.date(2018, 6, 24), Decimal('41.80')),
 ('97/553', datetime.date(2018, 6, 25), Decimal('904.14')),
 ('97/522', datetime.date(2018, 6, 28), Decimal('1962.13')),
 ('203339-13', datetime.date(2018, 7, 5), Decimal('17.50')),
 ('111-92R-10093', datetime.date(2018, 7, 6), Decimal('39.77')),
 ('111897', datetime.date(2018, 7, 15), Decimal('16.62')),
 ('111-92R-10095', datetime.date(2018, 7, 15), Decimal('32.70')),
 ('97-1024A', datetime.date(2018, 7, 20), Decimal('356.48')),
 ('9982771', datetime.date(2018, 7, 24), Decimal('503.20')),
 ('97/222', datetime.date(2018, 7, 25), Decimal('1000.46')),
 ('547480102', datetime.date(2018, 8, 1), Decimal('224.00'))]

In [9]:
%%sql # The same query restated with a subquery

SELECT invoice_number, invoice_date, invoice_total
FROM Invoices
WHERE vendor_id IN (
  SELECT vendor_id
  FROM Vendors
  WHERE vendor_state = 'CA')
ORDER BY invoice_date;

 * mysql+pymysql://w-alkao:***@localhost
40 rows affected.

[('97/488', datetime.date(2018, 4, 24), Decimal('601.95')),
 ('125520-1', datetime.date(2018, 4, 24), Decimal('95.00')),
 ('111-92R-10096', datetime.date(2018, 4, 30), Decimal('16.33')),
 ('25022117', datetime.date(2018, 5, 1), Decimal('6.00')),
 ('P02-88D77S7', datetime.date(2018, 5, 3), Decimal('856.92')),
 ('QP58872', datetime.date(2018, 5, 7), Decimal('116.54')),
 ('24863706', datetime.date(2018, 5, 10), Decimal('6.00')),
 ('10843', datetime.date(2018, 5, 11), Decimal('4901.26')),
 ('77290', datetime.date(2018, 5, 13), Decimal('1750.00')),
 ('121897', datetime.date(2018, 5, 19), Decimal('450.00')),
 ('97/486', datetime.date(2018, 5, 21), Decimal('953.10')),
 ('P02-3772', datetime.date(2018, 5, 21), Decimal('7125.34')),
 ('94007005', datetime.date(2018, 5, 23), Decimal('220.00')),
 ('97/465', datetime.date(2018, 5, 25), Decimal('565.15')),
 ('RTR-72-3662-X', datetime.date(2018, 5, 25), Decimal('1600.00')),
 ('97/503', datetime.date(2018, 5, 30), Decimal('639.77')),
 ('111-92R-10094', datetime.date(2018, 6, 1), Decimal('19.67')),
 ('547481328', datetime.date(2018, 6, 3), Decimal('224.00')),
 ('111-92R-10097', datetime.date(2018, 6, 4), Decimal('16.33')),
 ('547479217', datetime.date(2018, 6, 7), Decimal('116.00')),
 ('Q545443', datetime.date(2018, 6, 9), Decimal('1083.58')),
 ('111-92R-10092', datetime.date(2018, 6, 9), Decimal('46.21')),
 ('97/553B', datetime.date(2018, 6, 10), Decimal('313.55')),
 ('367447', datetime.date(2018, 6, 11), Decimal('2433.00')),
 ('24946731', datetime.date(2018, 6, 15), Decimal('25.67')),
 ('509786', datetime.date(2018, 6, 18), Decimal('6940.25')),
 ('MABO1489', datetime.date(2018, 6, 21), Decimal('936.93')),
 ('24780512', datetime.date(2018, 6, 22), Decimal('6.00')),
 ('CBM9920-M-T77109', datetime.date(2018, 6, 23), Decimal('290.00')),
 ('109596', datetime.date(2018, 6, 24), Decimal('41.80')),
 ('97/553', datetime.date(2018, 6, 25), Decimal('904.14')),
 ('97/522', datetime.date(2018, 6, 28), Decimal('1962.13')),
 ('203339-13', datetime.date(2018, 7, 5), Decimal('17.50')),
 ('111-92R-10093', datetime.date(2018, 7, 6), Decimal('39.77')),
 ('111897', datetime.date(2018, 7, 15), Decimal('16.62')),
 ('111-92R-10095', datetime.date(2018, 7, 15), Decimal('32.70')),
 ('97-1024A', datetime.date(2018, 7, 20), Decimal('356.48')),
 ('9982771', datetime.date(2018, 7, 24), Decimal('503.20')),
 ('97/222', datetime.date(2018, 7, 25), Decimal('1000.46')),
 ('547480102', datetime.date(2018, 8, 1), Decimal('224.00'))]

### Subqueries in the Where clause

In [5]:
%%sql # Get vendors without invoices

SELECT vendor_id, vendor_name, vendor_state
FROM Vendors
WHERE vendor_id NOT IN (
  SELECT DISTINCT vendor_id
  FROM Invoices)
ORDER BY vendor_id;

 * mysql+pymysql://w-alkao:***@localhost
88 rows affected.

[(1, 'US Postal Service', 'WI'),
 (2, 'National Information Data Ctr', 'DC'),
 (3, 'Register of Copyrights', 'DC'),
 (4, 'Jobtrak', 'CA'),
 (5, 'Newbrige Book Clubs', 'NJ'),
 (6, 'California Chamber Of Commerce', 'CA'),
 (7, "Towne Advertiser's Mailing Svcs", 'CA'),
 (8, 'BFI Industries', 'CA'),
 (9, 'Pacific Gas & Electric', 'CA'),
 (10, 'Robbins Mobile Lock And Key', 'CA'),
 (11, 'Bill Marvin Electric Inc', 'CA'),
 (12, 'City Of Fresno', 'CA'),
 (13, 'Golden Eagle Insurance Co', 'CA'),
 (14, 'Expedata Inc', 'CA'),
 (15, 'ASC Signs', 'CA'),
 (16, 'Internal Revenue Service', 'CA'),
 (17, 'Blanchard & Johnson Associates', 'CA'),
 (18, 'Fresno Photoengraving Company', 'CA'),
 (19, 'Crown Printing', 'CA'),
 (20, 'Diversified Printing & Pub', 'CA'),
 (21, 'The Library Ltd', 'MO'),
 (22, 'Micro Center', 'OH'),
 (23, 'Yale Industrial Trucks-Fresno', 'CA'),
 (24, 'Zee Medical Service Co', 'IA'),
 (25, 'California Data Marketing', 'CA'),
 (26, 'Small Press', 'MI'),
 (27, 'Rich Advertising', 'NJ'),
 (29, 'Vision Envelope & Printing', 'CA'),
 (30, 'Costco', 'CA'),
 (31, 'Enterprise Communications Inc', 'VA'),
 (32, 'RR Bowker', 'NJ'),
 (33, 'Nielson', 'OH'),
 (35, 'Cal State Termite', 'CA'),
 (36, 'Graylift', 'CA'),
 (38, "Venture Communications Int'l", 'NY'),
 (39, 'Custom Printing Company', 'MO'),
 (40, 'Nat Assoc of College Stores', 'OH'),
 (41, 'Shields Design', 'CA'),
 (42, 'Opamp Technical Books', 'CA'),
 (43, 'Capital Resource Credit', 'MN'),
 (44, 'Courier Companies, Inc', 'MA'),
 (45, 'Naylor Publications Inc', 'FL'),
 (46, 'Open Horizons Publishing', 'IA'),
 (47, 'Baker & Taylor Books', 'NC'),
 (49, 'Mcgraw Hill Companies', 'IL'),
 (50, 'Publishers Weekly', 'OH'),
 (51, 'Blue Shield of California', 'CA'),
 (52, 'Aztek Label', 'CA'),
 (53, 'Gary McKeighan Insurance', 'CA'),
 (54, 'Ph Photographic Services', 'CA'),
 (55, 'Quality Education Data', 'IL'),
 (56, 'Springhouse Corp', 'PA'),
 (57, 'The Windows Deck', 'CA'),
 (58, 'Fresno Rack & Shelving Inc', 'CA'),
 (59, 'Publishers Marketing Assoc', 'CA'),
 (60, 'The Mailers Guide Co', 'NY'),
 (61, 'American Booksellers Assoc', 'NY'),
 (62, 'Cmg Information Services', 'MA'),
 (63, "Lou Gentile's Flower Basket", 'CA'),
 (64, 'Texaco', 'CA'),
 (65, 'The Drawing Board', 'IL'),
 (66, 'Ascom Hasler Mailing Systems', 'CT'),
 (67, 'Bill Jones', 'CA'),
 (68, 'Computer Library', 'AZ'),
 (69, 'Frank E Wilber Co', 'CA'),
 (70, 'Fresno Credit Bureau', 'CA'),
 (71, 'The Fresno Bee', 'CA'),
 (73, 'Executive Office Products', 'CA'),
 (74, 'Leslie Company', 'KS'),
 (75, 'Retirement Plan Consultants', 'CA'),
 (76, 'Simon Direct Inc', 'NJ'),
 (77, 'State Board Of Equalization', 'CA'),
 (78, 'The Presort Center', 'CA'),
 (79, 'Valprint', 'CA'),
 (84, 'Boucher Communications Inc', 'PA'),
 (85, 'Champion Printing Company', 'OH'),
 (87, 'DMV Renewal', 'CA'),
 (91, 'McKesson Water Products', 'CA'),
 (92, 'Zip Print & Copy Center', 'CA'),
 (93, 'AT&T', 'AZ'),
 (98, 'American Express', 'CA'),
 (101, 'California Business Machines', 'CA'),
 (109, 'Kent H Landsberg Co', 'CA'),
 (111, 'Net Asset, Llc', 'CA'),
 (112, 'Office Depot', 'CA'),
 (116, 'State of California', 'CA'),
 (118, 'Unocal', 'CA'),
 (120, 'Dataforms/West', 'CA')]

In [6]:
%%sql # Same query without a subquery

SELECT v.vendor_id, vendor_name, vendor_state
FROM Vendors v 
  LEFT JOIN Invoices i ON v.vendor_id = i.vendor_id
WHERE i.vendor_id IS NULL
ORDER BY v.vendor_id;

 * mysql+pymysql://w-alkao:***@localhost
88 rows affected.

[(1, 'US Postal Service', 'WI'),
 (2, 'National Information Data Ctr', 'DC'),
 (3, 'Register of Copyrights', 'DC'),
 (4, 'Jobtrak', 'CA'),
 (5, 'Newbrige Book Clubs', 'NJ'),
 (6, 'California Chamber Of Commerce', 'CA'),
 (7, "Towne Advertiser's Mailing Svcs", 'CA'),
 (8, 'BFI Industries', 'CA'),
 (9, 'Pacific Gas & Electric', 'CA'),
 (10, 'Robbins Mobile Lock And Key', 'CA'),
 (11, 'Bill Marvin Electric Inc', 'CA'),
 (12, 'City Of Fresno', 'CA'),
 (13, 'Golden Eagle Insurance Co', 'CA'),
 (14, 'Expedata Inc', 'CA'),
 (15, 'ASC Signs', 'CA'),
 (16, 'Internal Revenue Service', 'CA'),
 (17, 'Blanchard & Johnson Associates', 'CA'),
 (18, 'Fresno Photoengraving Company', 'CA'),
 (19, 'Crown Printing', 'CA'),
 (20, 'Diversified Printing & Pub', 'CA'),
 (21, 'The Library Ltd', 'MO'),
 (22, 'Micro Center', 'OH'),
 (23, 'Yale Industrial Trucks-Fresno', 'CA'),
 (24, 'Zee Medical Service Co', 'IA'),
 (25, 'California Data Marketing', 'CA'),
 (26, 'Small Press', 'MI'),
 (27, 'Rich Advertising', 'NJ'),
 (29, 'Vision Envelope & Printing', 'CA'),
 (30, 'Costco', 'CA'),
 (31, 'Enterprise Communications Inc', 'VA'),
 (32, 'RR Bowker', 'NJ'),
 (33, 'Nielson', 'OH'),
 (35, 'Cal State Termite', 'CA'),
 (36, 'Graylift', 'CA'),
 (38, "Venture Communications Int'l", 'NY'),
 (39, 'Custom Printing Company', 'MO'),
 (40, 'Nat Assoc of College Stores', 'OH'),
 (41, 'Shields Design', 'CA'),
 (42, 'Opamp Technical Books', 'CA'),
 (43, 'Capital Resource Credit', 'MN'),
 (44, 'Courier Companies, Inc', 'MA'),
 (45, 'Naylor Publications Inc', 'FL'),
 (46, 'Open Horizons Publishing', 'IA'),
 (47, 'Baker & Taylor Books', 'NC'),
 (49, 'Mcgraw Hill Companies', 'IL'),
 (50, 'Publishers Weekly', 'OH'),
 (51, 'Blue Shield of California', 'CA'),
 (52, 'Aztek Label', 'CA'),
 (53, 'Gary McKeighan Insurance', 'CA'),
 (54, 'Ph Photographic Services', 'CA'),
 (55, 'Quality Education Data', 'IL'),
 (56, 'Springhouse Corp', 'PA'),
 (57, 'The Windows Deck', 'CA'),
 (58, 'Fresno Rack & Shelving Inc', 'CA'),
 (59, 'Publishers Marketing Assoc', 'CA'),
 (60, 'The Mailers Guide Co', 'NY'),
 (61, 'American Booksellers Assoc', 'NY'),
 (62, 'Cmg Information Services', 'MA'),
 (63, "Lou Gentile's Flower Basket", 'CA'),
 (64, 'Texaco', 'CA'),
 (65, 'The Drawing Board', 'IL'),
 (66, 'Ascom Hasler Mailing Systems', 'CT'),
 (67, 'Bill Jones', 'CA'),
 (68, 'Computer Library', 'AZ'),
 (69, 'Frank E Wilber Co', 'CA'),
 (70, 'Fresno Credit Bureau', 'CA'),
 (71, 'The Fresno Bee', 'CA'),
 (73, 'Executive Office Products', 'CA'),
 (74, 'Leslie Company', 'KS'),
 (75, 'Retirement Plan Consultants', 'CA'),
 (76, 'Simon Direct Inc', 'NJ'),
 (77, 'State Board Of Equalization', 'CA'),
 (78, 'The Presort Center', 'CA'),
 (79, 'Valprint', 'CA'),
 (84, 'Boucher Communications Inc', 'PA'),
 (85, 'Champion Printing Company', 'OH'),
 (87, 'DMV Renewal', 'CA'),
 (91, 'McKesson Water Products', 'CA'),
 (92, 'Zip Print & Copy Center', 'CA'),
 (93, 'AT&T', 'AZ'),
 (98, 'American Express', 'CA'),
 (101, 'California Business Machines', 'CA'),
 (109, 'Kent H Landsberg Co', 'CA'),
 (111, 'Net Asset, Llc', 'CA'),
 (112, 'Office Depot', 'CA'),
 (116, 'State of California', 'CA'),
 (118, 'Unocal', 'CA'),
 (120, 'Dataforms/West', 'CA')]

In [7]:
%%sql # Get invoices with a balance due less than the average

SELECT invoice_number, invoice_date,
  invoice_total - payment_total - credit_total AS balance_due
FROM Invoices
WHERE invoice_total - payment_total - credit_total > 0
  AND invoice_total - payment_total - credit_total < (
    SELECT AVG(invoice_total - payment_total - credit_total)
    FROM Invoices
    WHERE invoice_total - payment_total - credit_total > 0)
ORDER BY invoice_total DESC;

 * mysql+pymysql://w-alkao:***@localhost
11 rows affected.

[('31361833', datetime.date(2018, 7, 21), Decimal('579.42')),
 ('456792', datetime.date(2018, 8, 3), Decimal('565.60')),
 ('9982771', datetime.date(2018, 7, 24), Decimal('503.20')),
 ('456701', datetime.date(2018, 8, 2), Decimal('270.50')),
 ('547480102', datetime.date(2018, 8, 1), Decimal('224.00')),
 ('134116', datetime.date(2018, 7, 28), Decimal('90.36')),
 ('39104', datetime.date(2018, 7, 10), Decimal('85.31')),
 ('263253270', datetime.date(2018, 7, 22), Decimal('67.92')),
 ('263253268', datetime.date(2018, 7, 21), Decimal('59.97')),
 ('963253264', datetime.date(2018, 7, 18), Decimal('52.25')),
 ('263253273', datetime.date(2018, 7, 22), Decimal('30.75'))]

In [8]:
%%sql # Get invoices larger than the largest invoice for vendor 34

SELECT vendor_name, invoice_number, invoice_total
FROM Invoices i
  JOIN Vendors v ON i.vendor_id = v.vendor_id
WHERE invoice_total > ALL (
  SELECT invoice_total
  FROM Invoices
  WHERE vendor_id = 34)
ORDER BY vendor_name;

 * mysql+pymysql://w-alkao:***@localhost
28 rows affected.

[('Bertelsmann Industry Svcs. Inc', '509786', Decimal('6940.25')),
 ('Cahners Publishing Company', '587056', Decimal('2184.50')),
 ('Compuserve', '456791', Decimal('4390.00')),
 ('Compuserve', '456789', Decimal('8344.50')),
 ('Compuserve', '456789', Decimal('8344.50')),
 ('Computerworld', '367447', Decimal('2433.00')),
 ('Data Reproductions Corp', '40318', Decimal('21842.00')),
 ('Dean Witter Reynolds', '75C-90227', Decimal('1367.50')),
 ('Digital Dreamworks', 'P02-3772', Decimal('7125.34')),
 ('Franchise Tax Board', 'RTR-72-3662-X', Decimal('1600.00')),
 ('Ingram', '31359783', Decimal('1575.00')),
 ('Malloy Lithographing Inc', '0-2058', Decimal('37966.19')),
 ('Malloy Lithographing Inc', '0-2436', Decimal('10976.06')),
 ('Malloy Lithographing Inc', '0-2060', Decimal('23517.58')),
 ('Malloy Lithographing Inc', 'P-0608', Decimal('20551.18')),
 ('Malloy Lithographing Inc', 'P-0259', Decimal('26881.40')),
 ('Pollstar', '77290', Decimal('1750.00')),
 ('United Parcel Service', '989319-457', Decimal('3813.33')),
 ('United Parcel Service', '989319-447', Decimal('3689.99')),
 ('United Parcel Service', '989319-417', Decimal('2051.59')),
 ('United Parcel Service', '989319-467', Decimal('2318.03')),
 ('United Parcel Service', '989319-487', Decimal('1927.54')),
 ('United Parcel Service', '989319-427', Decimal('2115.81')),
 ('United Parcel Service', '989319-497', Decimal('2312.20')),
 ('United Parcel Service', '989319-477', Decimal('2184.11')),
 ('United Parcel Service', '989319-437', Decimal('2765.36')),
 ('Yesmed, Inc', '10843', Decimal('4901.26')),
 ('Zylka Design', '97/522', Decimal('1962.13'))]

In [9]:
%%sql # Get invoices smaller than the largest invoice for vendor 115

SELECT vendor_name, invoice_number, invoice_total
FROM Vendors v
  JOIN Invoices i ON i.vendor_id = v.vendor_id
WHERE invoice_total < ANY (
  SELECT invoice_total
  FROM Invoices
  WHERE vendor_id = 115)

 * mysql+pymysql://w-alkao:***@localhost
17 rows affected.

[('Federal Express Corporation', '963253251', Decimal('15.50')),
 ('Pacific Bell', '111-92R-10096', Decimal('16.33')),
 ('Roadway Package System, Inc', '25022117', Decimal('6.00')),
 ('Compuserve', '21-4748363', Decimal('9.95')),
 ('Federal Express Corporation', '4-321-2596', Decimal('10.00')),
 ('Roadway Package System, Inc', '24863706', Decimal('6.00')),
 ('Compuserve', '21-4923721', Decimal('9.95')),
 ('Federal Express Corporation', '4-342-8069', Decimal('10.00')),
 ('Pacific Bell', '111-92R-10094', Decimal('19.67')),
 ('Pacific Bell', '111-92R-10097', Decimal('16.33')),
 ('Federal Express Corporation', '4-314-3057', Decimal('13.75')),
 ('Federal Express Corporation', '963253267', Decimal('23.50')),
 ('Roadway Package System, Inc', '24780512', Decimal('6.00')),
 ('Federal Express Corporation', '43966316', Decimal('10.00')),
 ('Abbey Office Furnishings', '203339-13', Decimal('17.50')),
 ('Suburban Propane', '111897', Decimal('16.62')),
 ('Federal Express Corporation', '263253257', Decimal('22.57'))]

In [10]:
%%sql # same result with SOME keyword

SELECT vendor_name, invoice_number, invoice_total
FROM Vendors v
  JOIN Invoices i ON i.vendor_id = v.vendor_id
WHERE invoice_total < SOME (
  SELECT invoice_total
  FROM Invoices
  WHERE vendor_id = 115)

 * mysql+pymysql://w-alkao:***@localhost
17 rows affected.

[('Federal Express Corporation', '963253251', Decimal('15.50')),
 ('Pacific Bell', '111-92R-10096', Decimal('16.33')),
 ('Roadway Package System, Inc', '25022117', Decimal('6.00')),
 ('Compuserve', '21-4748363', Decimal('9.95')),
 ('Federal Express Corporation', '4-321-2596', Decimal('10.00')),
 ('Roadway Package System, Inc', '24863706', Decimal('6.00')),
 ('Compuserve', '21-4923721', Decimal('9.95')),
 ('Federal Express Corporation', '4-342-8069', Decimal('10.00')),
 ('Pacific Bell', '111-92R-10094', Decimal('19.67')),
 ('Pacific Bell', '111-92R-10097', Decimal('16.33')),
 ('Federal Express Corporation', '4-314-3057', Decimal('13.75')),
 ('Federal Express Corporation', '963253267', Decimal('23.50')),
 ('Roadway Package System, Inc', '24780512', Decimal('6.00')),
 ('Federal Express Corporation', '43966316', Decimal('10.00')),
 ('Abbey Office Furnishings', '203339-13', Decimal('17.50')),
 ('Suburban Propane', '111897', Decimal('16.62')),
 ('Federal Express Corporation', '263253257', Decimal('22.57'))]

In [15]:
%%sql # Get each invoice amount that's higher than the vendor's average invoice amount

SELECT vendor_id, invoice_number, invoice_total
FROM Invoices i
WHERE invoice_total > (
  SELECT AVG(invoice_total)
  FROM Invoices
  WHERE vendor_id = i.vendor_id)
ORDER BY vendor_id, invoice_total;

 * mysql+pymysql://w-alkao:***@localhost
39 rows affected.

[(34, 'Q545443', Decimal('1083.58')),
 (37, '547480102', Decimal('224.00')),
 (37, '547481328', Decimal('224.00')),
 (72, '40318', Decimal('21842.00')),
 (80, '133560', Decimal('175.00')),
 (83, '31359783', Decimal('1575.00')),
 (95, '111-92R-10095', Decimal('32.70')),
 (95, '111-92R-10093', Decimal('39.77')),
 (95, '111-92R-10092', Decimal('46.21')),
 (97, '456791', Decimal('4390.00')),
 (97, '456789', Decimal('8344.50')),
 (97, '456789', Decimal('8344.50')),
 (110, 'P-0259', Decimal('26881.40')),
 (110, '0-2058', Decimal('37966.19')),
 (115, '24946731', Decimal('25.67')),
 (121, '97/553', Decimal('904.14')),
 (121, '97/486', Decimal('953.10')),
 (121, '97/222', Decimal('1000.46')),
 (121, '97/522', Decimal('1962.13')),
 (122, '989319-437', Decimal('2765.36')),
 (122, '989319-447', Decimal('3689.99')),
 (122, '989319-457', Decimal('3813.33')),
 (123, '963253242', Decimal('104.00')),
 (123, '963253235', Decimal('108.25')),
 (123, '963253254', Decimal('108.50')),
 (123, '963253263', Decimal('109.50')),
 (123, '963253258', Decimal('111.00')),
 (123, '963253232', Decimal('127.75')),
 (123, '963253249', Decimal('127.75')),
 (123, '963253246', Decimal('129.00')),
 (123, '963253234', Decimal('138.75')),
 (123, '2-000-2993', Decimal('144.70')),
 (123, '963253239', Decimal('147.25')),
 (123, '963253271', Decimal('158.00')),
 (123, '4-327-7357', Decimal('162.75')),
 (123, '963253237', Decimal('172.50')),
 (123, '963253248', Decimal('241.00')),
 (123, '94007069', Decimal('400.00')),
 (123, '963253230', Decimal('739.20'))]

In [16]:
%%sql # Get all vendors that don't have invoices

SELECT vendor_id, vendor_name, vendor_state
FROM Vendors v
WHERE NOT EXISTS (
  SELECT * 
  FROM Invoices
  WHERE vendor_id = v.vendor_id)

 * mysql+pymysql://w-alkao:***@localhost
88 rows affected.

[(1, 'US Postal Service', 'WI'),
 (2, 'National Information Data Ctr', 'DC'),
 (3, 'Register of Copyrights', 'DC'),
 (4, 'Jobtrak', 'CA'),
 (5, 'Newbrige Book Clubs', 'NJ'),
 (6, 'California Chamber Of Commerce', 'CA'),
 (7, "Towne Advertiser's Mailing Svcs", 'CA'),
 (8, 'BFI Industries', 'CA'),
 (9, 'Pacific Gas & Electric', 'CA'),
 (10, 'Robbins Mobile Lock And Key', 'CA'),
 (11, 'Bill Marvin Electric Inc', 'CA'),
 (12, 'City Of Fresno', 'CA'),
 (13, 'Golden Eagle Insurance Co', 'CA'),
 (14, 'Expedata Inc', 'CA'),
 (15, 'ASC Signs', 'CA'),
 (16, 'Internal Revenue Service', 'CA'),
 (17, 'Blanchard & Johnson Associates', 'CA'),
 (18, 'Fresno Photoengraving Company', 'CA'),
 (19, 'Crown Printing', 'CA'),
 (20, 'Diversified Printing & Pub', 'CA'),
 (21, 'The Library Ltd', 'MO'),
 (22, 'Micro Center', 'OH'),
 (23, 'Yale Industrial Trucks-Fresno', 'CA'),
 (24, 'Zee Medical Service Co', 'IA'),
 (25, 'California Data Marketing', 'CA'),
 (26, 'Small Press', 'MI'),
 (27, 'Rich Advertising', 'NJ'),
 (29, 'Vision Envelope & Printing', 'CA'),
 (30, 'Costco', 'CA'),
 (31, 'Enterprise Communications Inc', 'VA'),
 (32, 'RR Bowker', 'NJ'),
 (33, 'Nielson', 'OH'),
 (35, 'Cal State Termite', 'CA'),
 (36, 'Graylift', 'CA'),
 (38, "Venture Communications Int'l", 'NY'),
 (39, 'Custom Printing Company', 'MO'),
 (40, 'Nat Assoc of College Stores', 'OH'),
 (41, 'Shields Design', 'CA'),
 (42, 'Opamp Technical Books', 'CA'),
 (43, 'Capital Resource Credit', 'MN'),
 (44, 'Courier Companies, Inc', 'MA'),
 (45, 'Naylor Publications Inc', 'FL'),
 (46, 'Open Horizons Publishing', 'IA'),
 (47, 'Baker & Taylor Books', 'NC'),
 (49, 'Mcgraw Hill Companies', 'IL'),
 (50, 'Publishers Weekly', 'OH'),
 (51, 'Blue Shield of California', 'CA'),
 (52, 'Aztek Label', 'CA'),
 (53, 'Gary McKeighan Insurance', 'CA'),
 (54, 'Ph Photographic Services', 'CA'),
 (55, 'Quality Education Data', 'IL'),
 (56, 'Springhouse Corp', 'PA'),
 (57, 'The Windows Deck', 'CA'),
 (58, 'Fresno Rack & Shelving Inc', 'CA'),
 (59, 'Publishers Marketing Assoc', 'CA'),
 (60, 'The Mailers Guide Co', 'NY'),
 (61, 'American Booksellers Assoc', 'NY'),
 (62, 'Cmg Information Services', 'MA'),
 (63, "Lou Gentile's Flower Basket", 'CA'),
 (64, 'Texaco', 'CA'),
 (65, 'The Drawing Board', 'IL'),
 (66, 'Ascom Hasler Mailing Systems', 'CT'),
 (67, 'Bill Jones', 'CA'),
 (68, 'Computer Library', 'AZ'),
 (69, 'Frank E Wilber Co', 'CA'),
 (70, 'Fresno Credit Bureau', 'CA'),
 (71, 'The Fresno Bee', 'CA'),
 (73, 'Executive Office Products', 'CA'),
 (74, 'Leslie Company', 'KS'),
 (75, 'Retirement Plan Consultants', 'CA'),
 (76, 'Simon Direct Inc', 'NJ'),
 (77, 'State Board Of Equalization', 'CA'),
 (78, 'The Presort Center', 'CA'),
 (79, 'Valprint', 'CA'),
 (84, 'Boucher Communications Inc', 'PA'),
 (85, 'Champion Printing Company', 'OH'),
 (87, 'DMV Renewal', 'CA'),
 (91, 'McKesson Water Products', 'CA'),
 (92, 'Zip Print & Copy Center', 'CA'),
 (93, 'AT&T', 'AZ'),
 (98, 'American Express', 'CA'),
 (101, 'California Business Machines', 'CA'),
 (109, 'Kent H Landsberg Co', 'CA'),
 (111, 'Net Asset, Llc', 'CA'),
 (112, 'Office Depot', 'CA'),
 (116, 'State of California', 'CA'),
 (118, 'Unocal', 'CA'),
 (120, 'Dataforms/West', 'CA')]

### Subqueries in other clauses (Select and From)

In [19]:
%%sql # Get most recent invoice date for each vendor

SELECT vendor_name,
  (SELECT MAX(invoice_date) FROM Invoices
    WHERE vendor_id = v.vendor_id) AS latest_inv
FROM Vendors v
ORDER BY latest_inv DESC;

 * mysql+pymysql://w-alkao:***@localhost
122 rows affected.

[('Compuserve', datetime.date(2018, 8, 3)),
 ('Federal Express Corporation', datetime.date(2018, 8, 2)),
 ('Blue Cross', datetime.date(2018, 8, 1)),
 ('Malloy Lithographing Inc', datetime.date(2018, 7, 31)),
 ('Cardinal Business Media, Inc.', datetime.date(2018, 7, 28)),
 ('Zylka Design', datetime.date(2018, 7, 25)),
 ('Ford Motor Credit Company', datetime.date(2018, 7, 24)),
 ('United Parcel Service', datetime.date(2018, 7, 24)),
 ('Ingram', datetime.date(2018, 7, 21)),
 ('Wakefield Co', datetime.date(2018, 7, 20)),
 ("Reiter's Scientific & Pro Books", datetime.date(2018, 7, 19)),
 ('Pacific Bell', datetime.date(2018, 7, 15)),
 ('Suburban Propane', datetime.date(2018, 7, 15)),
 ('Data Reproductions Corp', datetime.date(2018, 7, 10)),
 ('Abbey Office Furnishings', datetime.date(2018, 7, 5)),
 ('Cahners Publishing Company', datetime.date(2018, 6, 30)),
 ('Coffee Break Service', datetime.date(2018, 6, 24)),
 ('Postmaster', datetime.date(2018, 6, 23)),
 ('Roadway Package System, Inc', datetime.date(2018, 6, 22)),
 ('Wang Laboratories, Inc.', datetime.date(2018, 6, 21)),
 ('Bertelsmann Industry Svcs. Inc', datetime.date(2018, 6, 18)),
 ('Computerworld', datetime.date(2018, 6, 11)),
 ('Dean Witter Reynolds', datetime.date(2018, 6, 11)),
 ('IBM', datetime.date(2018, 6, 9)),
 ('Franchise Tax Board', datetime.date(2018, 5, 25)),
 ('Dristas Groom & McCormick', datetime.date(2018, 5, 23)),
 ('Digital Dreamworks', datetime.date(2018, 5, 21)),
 ('Gostanian General Building', datetime.date(2018, 5, 19)),
 ('Edward Data Services', datetime.date(2018, 5, 15)),
 ('Pollstar', datetime.date(2018, 5, 13)),
 ('Yesmed, Inc', datetime.date(2018, 5, 11)),
 ('Fresno County Tax Collector', datetime.date(2018, 5, 3)),
 ('Wells Fargo Bank', datetime.date(2018, 4, 26)),
 ('Evans Executone Inc', datetime.date(2018, 4, 24)),
 ('American Booksellers Assoc', None),
 ('American Express', None),
 ('ASC Signs', None),
 ('Ascom Hasler Mailing Systems', None),
 ('AT&T', None),
 ('Aztek Label', None),
 ('Baker & Taylor Books', None),
 ('BFI Industries', None),
 ('Bill Jones', None),
 ('Bill Marvin Electric Inc', None),
 ('Blanchard & Johnson Associates', None),
 ('Blue Shield of California', None),
 ('Boucher Communications Inc', None),
 ('Cal State Termite', None),
 ('California Business Machines', None),
 ('California Chamber Of Commerce', None),
 ('California Data Marketing', None),
 ('Capital Resource Credit', None),
 ('Champion Printing Company', None),
 ('City Of Fresno', None),
 ('Cmg Information Services', None),
 ('Computer Library', None),
 ('Costco', None),
 ('Courier Companies, Inc', None),
 ('Crown Printing', None),
 ('Custom Printing Company', None),
 ('Dataforms/West', None),
 ('Diversified Printing & Pub', None),
 ('DMV Renewal', None),
 ('Enterprise Communications Inc', None),
 ('Executive Office Products', None),
 ('Expedata Inc', None),
 ('Frank E Wilber Co', None),
 ('Fresno Credit Bureau', None),
 ('Fresno Photoengraving Company', None),
 ('Fresno Rack & Shelving Inc', None),
 ('Gary McKeighan Insurance', None),
 ('Golden Eagle Insurance Co', None),
 ('Graylift', None),
 ('Internal Revenue Service', None),
 ('Jobtrak', None),
 ('Kent H Landsberg Co', None),
 ('Leslie Company', None),
 ("Lou Gentile's Flower Basket", None),
 ('Mcgraw Hill Companies', None),
 ('McKesson Water Products', None),
 ('Micro Center', None),
 ('Nat Assoc of College Stores', None),
 ('National Information Data Ctr', None),
 ('Naylor Publications Inc', None),
 ('Net Asset, Llc', None),
 ('Newbrige Book Clubs', None),
 ('Nielson', None),
 ('Office Depot', None),
 ('Opamp Technical Books', None),
 ('Open Horizons Publishing', None),
 ('Pacific Gas & Electric', None),
 ('Ph Photographic Services', None),
 ('Publishers Marketing Assoc', None),
 ('Publishers Weekly', None),
 ('Quality Education Data', None),
 ('Register of Copyrights', None),
 ('Retirement Plan Consultants', None),
 ('Rich Advertising', None),
 ('Robbins Mobile Lock And Key', None),
 ('RR Bowker', None),
 ('Shields Design', None),
 ('Simon Direct Inc', None),
 ('Small Press', None),
 ('Springhouse Corp', None),
 ('State Board Of Equalization', None),
 ('State of California', None),
 ('Texaco', None),
 ('The Drawing Board', None),
 ('The Fresno Bee', None),
 ('The Library Ltd', None),
 ('The Mailers Guide Co', None),
 ('The Presort Center', None),
 ('The Windows Deck', None),
 ("Towne Advertiser's Mailing Svcs", None),
 ('Unocal', None),
 ('US Postal Service', None),
 ('Valprint', None),
 ("Venture Communications Int'l", None),
 ('Vision Envelope & Printing', None),
 ('Yale Industrial Trucks-Fresno', None),
 ('Zee Medical Service Co', None),
 ('Zip Print & Copy Center', None)]

In [20]:
%%sql # Same query restated using a join

SELECT vendor_name, MAX(invoice_date) AS latest_inv
FROM Vendors v
  LEFT JOIN Invoices i ON v.vendor_id = i.vendor_id
GROUP BY vendor_name
ORDER BY latest_inv DESC;

 * mysql+pymysql://w-alkao:***@localhost
122 rows affected.

[('Compuserve', datetime.date(2018, 8, 3)),
 ('Federal Express Corporation', datetime.date(2018, 8, 2)),
 ('Blue Cross', datetime.date(2018, 8, 1)),
 ('Malloy Lithographing Inc', datetime.date(2018, 7, 31)),
 ('Cardinal Business Media, Inc.', datetime.date(2018, 7, 28)),
 ('Zylka Design', datetime.date(2018, 7, 25)),
 ('Ford Motor Credit Company', datetime.date(2018, 7, 24)),
 ('United Parcel Service', datetime.date(2018, 7, 24)),
 ('Ingram', datetime.date(2018, 7, 21)),
 ('Wakefield Co', datetime.date(2018, 7, 20)),
 ("Reiter's Scientific & Pro Books", datetime.date(2018, 7, 19)),
 ('Pacific Bell', datetime.date(2018, 7, 15)),
 ('Suburban Propane', datetime.date(2018, 7, 15)),
 ('Data Reproductions Corp', datetime.date(2018, 7, 10)),
 ('Abbey Office Furnishings', datetime.date(2018, 7, 5)),
 ('Cahners Publishing Company', datetime.date(2018, 6, 30)),
 ('Coffee Break Service', datetime.date(2018, 6, 24)),
 ('Postmaster', datetime.date(2018, 6, 23)),
 ('Roadway Package System, Inc', datetime.date(2018, 6, 22)),
 ('Wang Laboratories, Inc.', datetime.date(2018, 6, 21)),
 ('Bertelsmann Industry Svcs. Inc', datetime.date(2018, 6, 18)),
 ('Computerworld', datetime.date(2018, 6, 11)),
 ('Dean Witter Reynolds', datetime.date(2018, 6, 11)),
 ('IBM', datetime.date(2018, 6, 9)),
 ('Franchise Tax Board', datetime.date(2018, 5, 25)),
 ('Dristas Groom & McCormick', datetime.date(2018, 5, 23)),
 ('Digital Dreamworks', datetime.date(2018, 5, 21)),
 ('Gostanian General Building', datetime.date(2018, 5, 19)),
 ('Edward Data Services', datetime.date(2018, 5, 15)),
 ('Pollstar', datetime.date(2018, 5, 13)),
 ('Yesmed, Inc', datetime.date(2018, 5, 11)),
 ('Fresno County Tax Collector', datetime.date(2018, 5, 3)),
 ('Wells Fargo Bank', datetime.date(2018, 4, 26)),
 ('Evans Executone Inc', datetime.date(2018, 4, 24)),
 ('American Booksellers Assoc', None),
 ('American Express', None),
 ('ASC Signs', None),
 ('Ascom Hasler Mailing Systems', None),
 ('AT&T', None),
 ('Aztek Label', None),
 ('Baker & Taylor Books', None),
 ('BFI Industries', None),
 ('Bill Jones', None),
 ('Bill Marvin Electric Inc', None),
 ('Blanchard & Johnson Associates', None),
 ('Blue Shield of California', None),
 ('Boucher Communications Inc', None),
 ('Cal State Termite', None),
 ('California Business Machines', None),
 ('California Chamber Of Commerce', None),
 ('California Data Marketing', None),
 ('Capital Resource Credit', None),
 ('Champion Printing Company', None),
 ('City Of Fresno', None),
 ('Cmg Information Services', None),
 ('Computer Library', None),
 ('Costco', None),
 ('Courier Companies, Inc', None),
 ('Crown Printing', None),
 ('Custom Printing Company', None),
 ('Dataforms/West', None),
 ('Diversified Printing & Pub', None),
 ('DMV Renewal', None),
 ('Enterprise Communications Inc', None),
 ('Executive Office Products', None),
 ('Expedata Inc', None),
 ('Frank E Wilber Co', None),
 ('Fresno Credit Bureau', None),
 ('Fresno Photoengraving Company', None),
 ('Fresno Rack & Shelving Inc', None),
 ('Gary McKeighan Insurance', None),
 ('Golden Eagle Insurance Co', None),
 ('Graylift', None),
 ('Internal Revenue Service', None),
 ('Jobtrak', None),
 ('Kent H Landsberg Co', None),
 ('Leslie Company', None),
 ("Lou Gentile's Flower Basket", None),
 ('Mcgraw Hill Companies', None),
 ('McKesson Water Products', None),
 ('Micro Center', None),
 ('Nat Assoc of College Stores', None),
 ('National Information Data Ctr', None),
 ('Naylor Publications Inc', None),
 ('Net Asset, Llc', None),
 ('Newbrige Book Clubs', None),
 ('Nielson', None),
 ('Office Depot', None),
 ('Opamp Technical Books', None),
 ('Open Horizons Publishing', None),
 ('Pacific Gas & Electric', None),
 ('Ph Photographic Services', None),
 ('Publishers Marketing Assoc', None),
 ('Publishers Weekly', None),
 ('Quality Education Data', None),
 ('Register of Copyrights', None),
 ('Retirement Plan Consultants', None),
 ('Rich Advertising', None),
 ('Robbins Mobile Lock And Key', None),
 ('RR Bowker', None),
 ('Shields Design', None),
 ('Simon Direct Inc', None),
 ('Small Press', None),
 ('Springhouse Corp', None),
 ('State Board Of Equalization', None),
 ('State of California', None),
 ('Texaco', None),
 ('The Drawing Board', None),
 ('The Fresno Bee', None),
 ('The Library Ltd', None),
 ('The Mailers Guide Co', None),
 ('The Presort Center', None),
 ('The Windows Deck', None),
 ("Towne Advertiser's Mailing Svcs", None),
 ('Unocal', None),
 ('US Postal Service', None),
 ('Valprint', None),
 ("Venture Communications Int'l", None),
 ('Vision Envelope & Printing', None),
 ('Yale Industrial Trucks-Fresno', None),
 ('Zee Medical Service Co', None),
 ('Zip Print & Copy Center', None)]

In [21]:
%%sql # Get the largest invoice total for the top vendor in each state

SELECT vendor_state, MAX(sum_of_invoices) AS max_sum_inv
FROM (
  SELECT vendor_state, vendor_name, SUM(invoice_total) AS sum_of_invoices
  FROM Vendors v
    JOIN Invoices i ON v.vendor_id = i.vendor_id
  GROUP BY vendor_state, vendor_name) t
GROUP BY vendor_state
ORDER BY vendor_state;

 * mysql+pymysql://w-alkao:***@localhost
10 rows affected.

[('AZ', Decimal('662.00')),
 ('CA', Decimal('7125.34')),
 ('DC', Decimal('600.00')),
 ('MA', Decimal('1367.50')),
 ('MI', Decimal('119892.41')),
 ('NV', Decimal('23177.96')),
 ('OH', Decimal('21935.00')),
 ('PA', Decimal('265.36')),
 ('TN', Decimal('4378.02')),
 ('TX', Decimal('2154.42'))]

In [23]:
%%sql # Result of the subquery (an inline view)

SELECT vendor_state, vendor_name, SUM(invoice_total) AS sum_of_invoices
FROM Vendors v
  JOIN Invoices i ON i.vendor_id = v.vendor_id
GROUP BY vendor_state, vendor_name
ORDER BY vendor_state;

 * mysql+pymysql://w-alkao:***@localhost
34 rows affected.

[('AZ', 'Wells Fargo Bank', Decimal('662.00')),
 ('CA', 'Abbey Office Furnishings', Decimal('17.50')),
 ('CA', 'Bertelsmann Industry Svcs. Inc', Decimal('6940.25')),
 ('CA', 'Blue Cross', Decimal('564.00')),
 ('CA', 'Coffee Break Service', Decimal('41.80')),
 ('CA', 'Computerworld', Decimal('2433.00')),
 ('CA', 'Digital Dreamworks', Decimal('7125.34')),
 ('CA', 'Dristas Groom & McCormick', Decimal('220.00')),
 ('CA', 'Evans Executone Inc', Decimal('95.00')),
 ('CA', 'Ford Motor Credit Company', Decimal('503.20')),
 ('CA', 'Franchise Tax Board', Decimal('1600.00')),
 ('CA', 'Fresno County Tax Collector', Decimal('856.92')),
 ('CA', 'Gostanian General Building', Decimal('450.00')),
 ('CA', 'IBM', Decimal('1200.12')),
 ('CA', 'Pacific Bell', Decimal('171.01')),
 ('CA', 'Pollstar', Decimal('1750.00')),
 ('CA', 'Postmaster', Decimal('290.00')),
 ('CA', 'Roadway Package System, Inc', Decimal('43.67')),
 ('CA', 'Suburban Propane', Decimal('16.62')),
 ('CA', 'Wakefield Co', Decimal('356.48')),
 ('CA', 'Wang Laboratories, Inc.', Decimal('936.93')),
 ('CA', 'Yesmed, Inc', Decimal('4901.26')),
 ('CA', 'Zylka Design', Decimal('6940.25')),
 ('DC', "Reiter's Scientific & Pro Books", Decimal('600.00')),
 ('MA', 'Dean Witter Reynolds', Decimal('1367.50')),
 ('MI', 'Data Reproductions Corp', Decimal('21927.31')),
 ('MI', 'Malloy Lithographing Inc', Decimal('119892.41')),
 ('NV', 'Cahners Publishing Company', Decimal('2184.50')),
 ('NV', 'United Parcel Service', Decimal('23177.96')),
 ('OH', 'Compuserve', Decimal('21935.00')),
 ('OH', 'Edward Data Services', Decimal('207.78')),
 ('PA', 'Cardinal Business Media, Inc.', Decimal('265.36')),
 ('TN', 'Federal Express Corporation', Decimal('4378.02')),
 ('TX', 'Ingram', Decimal('2154.42'))]

### Work with complex queries

In [5]:
%%sql # a complex query that uses three subqueries,
      # Which vendor in each state has the largest invoice total ?

SELECT t1.vendor_state, vendor_name, t1.sum_of_invoices
FROM (
  SELECT vendor_state, vendor_name, SUM(invoice_total) AS sum_of_invoices
  FROM Vendors v
    JOIN Invoices i ON i.vendor_id = v.vendor_id
  GROUP BY vendor_state, vendor_name) t1
    JOIN (
      SELECT vendor_state, MAX(sum_of_invoices) AS sum_of_invoices
      FROM (
        SELECT vendor_state, vendor_name, SUM(invoice_total) AS sum_of_invoices
        FROM Vendors v
          JOIN Invoices i ON v.vendor_id = i.vendor_id
        GROUP BY vendor_state, vendor_name) t2
      GROUP BY vendor_state) t3
  ON t1.vendor_state = t3.vendor_state AND t1.sum_of_invoices = t3.sum_of_invoices
ORDER BY vendor_state

 * mysql+pymysql://w-alkao:***@localhost
10 rows affected.

[('AZ', 'Wells Fargo Bank', Decimal('662.00')),
 ('CA', 'Digital Dreamworks', Decimal('7125.34')),
 ('DC', "Reiter's Scientific & Pro Books", Decimal('600.00')),
 ('MA', 'Dean Witter Reynolds', Decimal('1367.50')),
 ('MI', 'Malloy Lithographing Inc', Decimal('119892.41')),
 ('NV', 'United Parcel Service', Decimal('23177.96')),
 ('OH', 'Compuserve', Decimal('21935.00')),
 ('PA', 'Cardinal Business Media, Inc.', Decimal('265.36')),
 ('TN', 'Federal Express Corporation', Decimal('4378.02')),
 ('TX', 'Ingram', Decimal('2154.42'))]

In [6]:
%%sql # code for the first subquery

SELECT vendor_state, vendor_name, SUM(invoice_total) AS sum_of_invoices
FROM Vendors v
  JOIN Invoices i ON v.vendor_id = i.vendor_id
GROUP BY vendor_state, vendor_name;

 * mysql+pymysql://w-alkao:***@localhost
34 rows affected.

[('NV', 'United Parcel Service', Decimal('23177.96')),
 ('TN', 'Federal Express Corporation', Decimal('4378.02')),
 ('CA', 'Evans Executone Inc', Decimal('95.00')),
 ('CA', 'Zylka Design', Decimal('6940.25')),
 ('AZ', 'Wells Fargo Bank', Decimal('662.00')),
 ('CA', 'Pacific Bell', Decimal('171.01')),
 ('CA', 'Roadway Package System, Inc', Decimal('43.67')),
 ('CA', 'Fresno County Tax Collector', Decimal('856.92')),
 ('OH', 'Compuserve', Decimal('21935.00')),
 ('CA', 'IBM', Decimal('1200.12')),
 ('CA', 'Yesmed, Inc', Decimal('4901.26')),
 ('CA', 'Pollstar', Decimal('1750.00')),
 ('OH', 'Edward Data Services', Decimal('207.78')),
 ('CA', 'Gostanian General Building', Decimal('450.00')),
 ('CA', 'Digital Dreamworks', Decimal('7125.34')),
 ('CA', 'Dristas Groom & McCormick', Decimal('220.00')),
 ('CA', 'Franchise Tax Board', Decimal('1600.00')),
 ('MI', 'Malloy Lithographing Inc', Decimal('119892.41')),
 ('MI', 'Data Reproductions Corp', Decimal('21927.31')),
 ('CA', 'Blue Cross', Decimal('564.00')),
 ('TX', 'Ingram', Decimal('2154.42')),
 ('CA', 'Computerworld', Decimal('2433.00')),
 ('MA', 'Dean Witter Reynolds', Decimal('1367.50')),
 ('CA', 'Bertelsmann Industry Svcs. Inc', Decimal('6940.25')),
 ('CA', 'Wang Laboratories, Inc.', Decimal('936.93')),
 ('PA', 'Cardinal Business Media, Inc.', Decimal('265.36')),
 ('CA', 'Postmaster', Decimal('290.00')),
 ('CA', 'Coffee Break Service', Decimal('41.80')),
 ('NV', 'Cahners Publishing Company', Decimal('2184.50')),
 ('CA', 'Abbey Office Furnishings', Decimal('17.50')),
 ('CA', 'Suburban Propane', Decimal('16.62')),
 ('DC', "Reiter's Scientific & Pro Books", Decimal('600.00')),
 ('CA', 'Wakefield Co', Decimal('356.48')),
 ('CA', 'Ford Motor Credit Company', Decimal('503.20'))]

In [7]:
%%sql # The code for the second subquery

SELECT vendor_state, MAX(sum_of_invoices) AS sum_of_invoices
FROM (
  SELECT vendor_state, vendor_name, SUM(invoice_total) AS sum_of_invoices
  FROM Vendors v
    JOIN Invoices i ON v.vendor_id = i.vendor_id
  GROUP BY vendor_state, vendor_name) t
GROUP BY vendor_state;

 * mysql+pymysql://w-alkao:***@localhost
10 rows affected.

[('NV', Decimal('23177.96')),
 ('TN', Decimal('4378.02')),
 ('CA', Decimal('7125.34')),
 ('AZ', Decimal('662.00')),
 ('OH', Decimal('21935.00')),
 ('MI', Decimal('119892.41')),
 ('TX', Decimal('2154.42')),
 ('MA', Decimal('1367.50')),
 ('PA', Decimal('265.36')),
 ('DC', Decimal('600.00'))]

### Work with common table expressions

In [7]:
%%sql # The previous complex query rewrite with cte

WITH summary AS (
  SELECT vendor_state, vendor_name, SUM(invoice_total) AS sum_of_invoices
  FROM Vendors v
    JOIN Invoices i ON i.vendor_id = v.vendor_id
  GROUP BY vendor_state, vendor_name),
top_in_state AS (
  SELECT vendor_state, MAX(sum_of_invoices) AS sum_of_invoices
  FROM summary
  GROUP BY vendor_state)
SELECT s.vendor_state, s.vendor_name, t.sum_of_invoices
FROM summary s JOIN top_in_state t
  ON s.vendor_state = t.vendor_state AND s.sum_of_invoices = t.sum_of_invoices
ORDER BY s.vendor_state;

 * mysql+pymysql://w-alkao:***@localhost
10 rows affected.

[('AZ', 'Wells Fargo Bank', Decimal('662.00')),
 ('CA', 'Digital Dreamworks', Decimal('7125.34')),
 ('DC', "Reiter's Scientific & Pro Books", Decimal('600.00')),
 ('MA', 'Dean Witter Reynolds', Decimal('1367.50')),
 ('MI', 'Malloy Lithographing Inc', Decimal('119892.41')),
 ('NV', 'United Parcel Service', Decimal('23177.96')),
 ('OH', 'Compuserve', Decimal('21935.00')),
 ('PA', 'Cardinal Business Media, Inc.', Decimal('265.36')),
 ('TN', 'Federal Express Corporation', Decimal('4378.02')),
 ('TX', 'Ingram', Decimal('2154.42'))]

### Recursive CTE

In [9]:
%sql USE ex;

 * mysql+pymysql://w-alkao:***@localhost
0 rows affected.

[]

In [10]:
%sql SHOW TABLES;

 * mysql+pymysql://w-alkao:***@localhost
14 rows affected.

[('Active_invoices',),
 ('Color_sample',),
 ('Customers',),
 ('Date_sample',),
 ('Departments',),
 ('Employees',),
 ('Engine_sample',),
 ('Float_sample',),
 ('Null_sample',),
 ('Paid_invoices',),
 ('Projects',),
 ('Sales_reps',),
 ('Sales_totals',),
 ('String_sample',)]

In [11]:
%sql SELECT * FROM Employees;

 * mysql+pymysql://w-alkao:***@localhost
9 rows affected.

[(1, 'Smith', 'Cindy', 2, None),
 (2, 'Jones', 'Elmer', 4, 1),
 (3, 'Simonian', 'Ralph', 2, 2),
 (4, 'Hernandez', 'Olivia', 1, 9),
 (5, 'Aaronsen', 'Robert', 2, 4),
 (6, 'Watson', 'Denise', 6, 8),
 (7, 'Hardy', 'Thomas', 5, 2),
 (8, "O'Leary", 'Rhea', 4, 9),
 (9, 'Locario', 'Paulo', 6, 1)]

In [12]:
%%sql # Recursive cte that returns hierarchical data

WITH RECURSIVE employees_cte AS (
  SELECT employee_id,
    CONCAT(first_name, ' ', last_name) AS employee_name, 1 AS ranking
  FROM Employees
  WHERE manager_id is NULL
  UNION
  SELECT e.employee_id,
    CONCAT(first_name, ' ', last_name), ranking + 1
  FROM Employees e
    JOIN employees_cte ON e.manager_id = employees_cte.employee_id)
SELECT * 
FROM employees_cte
ORDER BY ranking, employee_id;

 * mysql+pymysql://w-alkao:***@localhost
9 rows affected.

[(1, 'Cindy Smith', 1),
 (2, 'Elmer Jones', 2),
 (9, 'Paulo Locario', 2),
 (3, 'Ralph Simonian', 3),
 (4, 'Olivia Hernandez', 3),
 (7, 'Thomas Hardy', 3),
 (8, "Rhea O'Leary", 3),
 (5, 'Robert Aaronsen', 4),
 (6, 'Denise Watson', 4)]

### Extra